version: "3"
services:
  app:
    build: .
    depends_on:
       - postgres
  
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  